# Generated by Django 4.2.4 on 2023-08-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_alter_story_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
