# Generated by Django 4.2.4 on 2023-08-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_alter_story_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='picture',
            field=models.URLField(blank=True, default='https://png.pngtree.com/png-clipart/20190924/original/pngtree-vector-book-icon-png-image_4869088.jpg', null=True),
        ),
    ]
