# Generated by Django 4.2.4 on 2023-08-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_todoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['category']},
        ),
    ]
