# Generated by Django 4.2.4 on 2023-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_diaryuser_first_name_diaryuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
