# Generated by Django 4.2.4 on 2023-08-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_diaryuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
