# Generated by Django 4.2.4 on 2023-08-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_diaryuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryuser',
            name='is_active',
        ),
    ]
