# Generated by Django 4.2.4 on 2023-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
