# Generated by Django 4.2.4 on 2023-08-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_date_alter_story_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['date']},
        ),
    ]
