# Generated by Django 4.2.4 on 2023-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_story_unique_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(),
        ),
    ]
