# Generated by Django 4.2.4 on 2023-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_remove_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
