# Generated by Django 4.2.4 on 2023-08-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneruser',
            name='phone_number',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
