# Generated by Django 4.2.4 on 2023-08-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partneruser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachUser',
            fields=[
                ('partneruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='partners.partneruser')),
            ],
            bases=('partners.partneruser',),
        ),
        migrations.CreateModel(
            name='FamilyUser',
            fields=[
                ('partneruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='partners.partneruser')),
            ],
            bases=('partners.partneruser',),
        ),
        migrations.CreateModel(
            name='HealthUser',
            fields=[
                ('partneruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='partners.partneruser')),
            ],
            bases=('partners.partneruser',),
        ),
        migrations.CreateModel(
            name='JobCoachUser',
            fields=[
                ('partneruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='partners.partneruser')),
            ],
            bases=('partners.partneruser',),
        ),
        migrations.CreateModel(
            name='LifeCoachUser',
            fields=[
                ('partneruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='partners.partneruser')),
            ],
            bases=('partners.partneruser',),
        ),
    ]
