# Generated by Django 4.2.4 on 2023-08-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_coachuser_familyuser_healthuser_jobcoachuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyuser',
            name='partneruser_ptr',
        ),
        migrations.RemoveField(
            model_name='healthuser',
            name='partneruser_ptr',
        ),
        migrations.RemoveField(
            model_name='jobcoachuser',
            name='partneruser_ptr',
        ),
        migrations.RemoveField(
            model_name='lifecoachuser',
            name='partneruser_ptr',
        ),
        migrations.AddField(
            model_name='partneruser',
            name='type_partner',
            field=models.IntegerField(choices=[(1, 'LIFE_COACH'), (2, 'DOCTOR'), (3, 'LOVE_COACH'), (4, 'JOB_COACH')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CoachUser',
        ),
        migrations.DeleteModel(
            name='FamilyUser',
        ),
        migrations.DeleteModel(
            name='HealthUser',
        ),
        migrations.DeleteModel(
            name='JobCoachUser',
        ),
        migrations.DeleteModel(
            name='LifeCoachUser',
        ),
    ]
